export const keys = [
  // 'createdAt',
  // 'updatedAt',
  'name',
  'company',
  'phoneNumber',
  // 'cities',
  'stars',
  'experience',
  'activityRange',
  'jobTitle',
  'officePhoneNumber',
  'directPhoneNumber',
  'email',
  'office',
  'website',
  // 'contacts',
  'facebook',
  'instagram',
  'tiktok',
  'twitter',
  'linkedIn',
  'realtor',
  'coldwell',
  'svn',
  'id',
  // 'board',
  'emailed',
  'hammond',
  'compass',
] as const;
